# ชื่อ: CI/CD พร้อม Cache และการปรับแต่งสำหรับ Production
name: CI/CD with Cache and Optimizations (Production Ready)

# กำหนดเงื่อนไขที่จะทำให้ workflow นี้ทำงาน
on:
  push:
    branches:
      - main  # เมื่อมีการ push ไปยัง branch main
  pull_request:
    types: [opened, synchronize, reopened]  # เมื่อมีการสร้าง PR ใหม่ หรือ update PR

jobs:
  # Job แรก: สร้าง, ทดสอบ และวิเคราะห์โค้ด
  build-and-test:
    name: Build, Test and Analyze
    runs-on: ubuntu-24.04  # ใช้ Ubuntu 24.04 เป็น environment
    steps:
      # ขั้นตอนที่ 1: ดาวน์โหลดโค้ดจาก repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ดาวน์โหลด history ทั้งหมดสำหรับ SonarCloud

      # ขั้นตอนที่ 2: ติดตั้ง Node.js พร้อม cache สำหรับ npm
      - name: Set up Node.js with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "18"  # ใช้ Node.js เวอร์ชัน 18
          cache: "npm"        # เปิดใช้ cache สำหรับ npm

      # ขั้นตอนที่ 3: Cache node_modules เพื่อเพิ่มความเร็ว
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules  # path ที่จะ cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  # key ที่ใช้ระบุ cache
          restore-keys: |
            ${{ runner.os }}-node-  # fallback key หาก exact match ไม่พบ

      # ขั้นตอนที่ 4: ติดตั้ง dependencies (ถ้ายังไม่มีใน cache)
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'  # ทำงานเฉพาะเมื่อไม่มีใน cache
        run: npm ci  # ใช้ npm ci แทน npm install เพื่อความเร็วและความแม่นยำ

      # ขั้นตอนที่ 5: แสดงข้อความเมื่อใช้ cache
      - name: Show message if dependencies are restored from cache
        if: steps.cache-node-modules.outputs.cache-hit == 'true'  # ทำงานเฉพาะเมื่อใช้ cache
        run: echo "✅ Dependencies restored from cache. Skipping installation."

      # ขั้นตอนที่ 6: ตรวจสอบช่องโหว่ด้านความปลอดภัย
      - name: Run security audit
        run: npm audit --audit-level=moderate  # ตรวจสอบ vulnerability ระดับ moderate ขึ้นไป
        continue-on-error: false # <--- จุดสำคัญ: หยุด workflow ถ้าพบปัญหาความปลอดภัย

      # ขั้นตอนที่ 7: รันการทดสอบ
      - name: Run tests
        run: npm run test:ci # <--- จุดสำคัญ: หยุด workflow ถ้าการทดสอบล้มเหลว
        env:
          NODE_ENV: test  # กำหนด environment เป็น test

      # ขั้นตอนที่ 8: วิเคราะห์คุณภาพโค้ดด้วย SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token สำหรับ GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Token สำหรับ SonarCloud
        with:
          projectBaseDir: .  # directory ที่จะวิเคราะห์

  # Job ที่สอง: Deploy ไปยัง Google Cloud Run
  deploy:
    name: Deploy to Cloud Run
    needs: build-and-test # <--- Job นี้จะทำงานต่อเมื่อ build-and-test สำเร็จเท่านั้น
    runs-on: ubuntu-24.04
    # เงื่อนไข: ทำงานเฉพาะเมื่อ push ไปยัง main branch เท่านั้น
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      # ขั้นตอนที่ 1: ดาวน์โหลดโค้ดอีกครั้งสำหรับ deployment
      - name: Checkout code
        uses: actions/checkout@v4

      # ขั้นตอนที่ 2: ยืนยันตัวตนกับ Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"  # Service Account Key

      # ขั้นตอนที่ 3: ติดตั้ง gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP Project ID

      # ขั้นตอนที่ 4: Deploy ไปยัง Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --source . \                                    # ใช้โค้ดจาก current directory
            --region ${{ secrets.GCP_REGION }} \           # region ที่จะ deploy
            --platform managed \                           # ใช้ fully managed Cloud Run
            --allow-unauthenticated \                      # อนุญาตให้เข้าถึงโดยไม่ต้อง authentication
            --memory 512Mi \                               # จำกัด memory ที่ 512MB
            --cpu 1 \                                      # ใช้ 1 CPU
            --max-instances 5 \                            # จำกัดจำนวน instance สูงสุดที่ 5
            --timeout 300 \                                # timeout 300 วินาที (5 นาที)
            --concurrency 80 \                             # จำนวน request พร้อมกันสูงสุดต่อ instance
            --set-env-vars NODE_ENV=production,NODE_OPTIONS=--experimental-vm-modules \ # ตั้งค่า environment variables
            --quiet                                        # ไม่แสดงข้อความ interactive

      # ขั้นตอนที่ 5: รับ URL ของ service ที่ deploy แล้ว
      - name: Get deployment URL
        id: get_url
        run: |
          # ดึง URL ของ service ที่เพิ่ง deploy
          SERVICE_URL=$(gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --format 'value(status.url)')
          # เก็บ URL ไว้ใน output เพื่อใช้ในขั้นตอนถัดไป
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
          echo "🚀 Application deployed successfully!"
          echo "📱 Service URL: $SERVICE_URL"

      # ขั้นตอนที่ 6: ตรวจสอบการ deploy ว่าสำเร็จหรือไม่
      - name: Verify deployment (Improved)
        run: |
          SERVICE_URL="${{ steps.get_url.outputs.SERVICE_URL }}"
          echo "Waiting for service to be ready..."
          
          # กำหนดค่าสำหรับการลองซ้ำ
          max_attempts=12      # ลองสูงสุด 12 ครั้ง
          attempt_num=1        # เริ่มจากครั้งที่ 1
          wait_seconds=10      # รอ 10 วินาทีระหว่างการลองแต่ละครั้ง
          
          # วนลูปเพื่อตรวจสอบ health check
          while [ $attempt_num -le $max_attempts ]; do
            echo "Attempt $attempt_num/$max_attempts: Testing health endpoint $SERVICE_URL/health"
            # ส่ง HTTP request ไปยัง /health endpoint
            response_code=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/health")
            
            # ถ้า response code เป็น 200 แสดงว่าสำเร็จ
            if [ "$response_code" -eq 200 ]; then
              echo "✅ Health check successful!"
              exit 0  # จบการทำงานด้วยสถานะสำเร็จ
            fi
            
            # ถ้ายังไม่สำเร็จ ให้รอแล้วลองใหม่
            echo "Health check failed with status $response_code. Waiting $wait_seconds seconds..."
            sleep $wait_seconds
            attempt_num=$((attempt_num+1))
          done
          
          # ถ้าลองครบแล้วยังไม่สำเร็จ
          echo "⚠️ Health check failed after $max_attempts attempts."
          exit 1 # <--- ทำให้ Workflow fail ถ้า health check ไม่ผ่านหลังจากลองครบแล้ว