# name: CI with SonarCloud + Deploy to GCP (Optimized & Fixed)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build, Test and Analyze
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18"
          cache: "npm"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2 - CORRECTED SHA
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Show message if dependencies restored from cache
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: echo "Dependencies restored from cache."

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: false

      - name: Run tests
        run: npm run test:ci
        env:
          NODE_ENV: test

      - name: Cache SonarCloud packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2 - CORRECTED SHA
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@67dbf889755728758178142b739969a08777d331 # v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .

  deploy:
    name: Deploy to Cloud Run
    needs: build-and-test
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@55bd3a7cf7809941d071235f099831014828893c # v2.1.3
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@2503748709498582100775903891a31f0f902612 # v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --source . \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 5 \
            --timeout 300 \
            --concurrency 80 \
            --set-env-vars NODE_ENV=production,NODE_OPTIONS=--experimental-vm-modules \
            --quiet
          
      - name: Get deployment URL
        id: get_url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --format 'value(status.url)')
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
          echo "🚀 Application deployed successfully!"
          echo "📱 Service URL: $SERVICE_URL"
          echo "🏥 Health Check: $SERVICE_URL/health"

      - name: Verify deployment
        run: |
          SERVICE_URL="${{ steps.get_url.outputs.SERVICE_URL }}"
          echo "Waiting for service to be ready..."
          max_attempts=12
          attempt_num=1
          wait_seconds=10
          while [ $attempt_num -le $max_attempts ]; do
            echo "Attempt $attempt_num/$max_attempts: Testing health endpoint $SERVICE_URL/health"
            response_code=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/health")
            if [ "$response_code" -eq 200 ]; then
              echo "✅ Health check successful!"
              exit 0
            fi
            echo "Health check failed with status $response_code. Waiting $wait_seconds seconds..."
            sleep $wait_seconds
            attempt_num=$((attempt_num+1))
          done
          echo "⚠️ Health check failed after $max_attempts attempts, but deployment completed. Please check the service manually."