
name: CI with SonarCloud + Deploy to GCP (Optimized & Standardized) # ชื่อ Workflow ที่แสดงในแท็บ Actions

on:
  push:
    branches:
      - main # ทำงานเมื่อมีการ push ไปยัง branch main
  pull_request:
    types: [opened, synchronize, reopened] # ทำงานเมื่อมีการสร้าง อัปเดต หรือเปิด PR ใหม่

jobs:
  build-and-test:
    name: Build, Test and Analyze # ชื่องาน CI: Build, Test และ Code Analysis
    runs-on: ubuntu-24.04 # ใช้ runner Ubuntu เวอร์ชันล่าสุด
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 - ดึงโค้ดจาก GitHub repository
        with:
          fetch-depth: 0 # ดึง commit history ทั้งหมด เพื่อให้ SonarCloud วิเคราะห์ได้ถูกต้อง

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2 - ติดตั้ง Node.js บน runner
        with:
          node-version: "18" # ใช้ Node.js เวอร์ชัน 18
          cache: "npm" # เปิดใช้ npm global cache เพื่อความเร็ว

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@ab5e74ddd6150b37941690929790884114729329 # v4.0.2
        with:
          path: node_modules # Path to cache node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true' # รัน npm ci เฉพาะเมื่อไม่มี cache hit สำหรับ node_modules
        run: npm ci # ติดตั้ง dependencies (เร็วกว่า npm install)

      - name: Install dependencies (from cache)
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: echo "Dependencies restored from cache." # แจ้งว่าใช้ dependencies จาก cache

      - name: Run security audit
        run: npm audit --audit-level=moderate # ตรวจสอบ security vulnerabilities
        continue-on-error: false # หยุด workflow หากพบปัญหาความปลอดภัย

      - name: Run tests
        run: npm run test:ci # รัน unit tests พร้อม coverage report
        env:
          NODE_ENV: test # ตั้งค่า environment เป็น test

      - name: Cache SonarCloud packages
        uses: actions/cache@ab5e74ddd6150b37941690929790884114729329 # v4.0.2
        with:
          path: ~/.sonar/cache # Path to cache for SonarCloud scanner
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/package-lock.json') }} # Key ควรจะอิงกับ lockfile ด้วยเผื่อมีการเปลี่ยนแปลง tool versions ที่ Sonar ใช้
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@67dbf889755728758178142b739969a08777d331 # v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token สำหรับ PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarCloud token จาก GitHub Secrets
        with:
          projectBaseDir: . # ระบุ root directory ของโปรเจค

  deploy:
    name: Deploy to Cloud Run # ชื่องาน: Deploy ไปยัง Google Cloud Run
    needs: build-and-test # รอให้ job build-and-test เสร็จก่อน
    runs-on: ubuntu-24.04 # ใช้ runner Ubuntu เวอร์ชันล่าสุด
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Deploy เฉพาะเมื่อ push ไปยัง main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 - ดึงโค้ดสำหรับ deployment

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@55bd3a7cf7809941d071235f099831014828893c # v2.1.3 - เชื่อมต่อกับ Google Cloud
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}" # ใช้ Service Account key จาก GitHub Secrets

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@2503748709498582100775903891a31f0f902612 # v2.1.0 - ติดตั้งและตั้งค่า gcloud CLI
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }} # ระบุ Google Cloud Project ID

      - name: Deploy to Cloud Run
        run: | # คำสั่ง deploy ไปยัง Cloud Run
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --source . \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 5 \
            --timeout 300 \
            --concurrency 80 \
            --set-env-vars NODE_ENV=production,NODE_OPTIONS=--experimental-vm-modules \
            --quiet

      - name: Get deployment URL
        id: get_url # Add an id to this step to reference its output
        run: | # ดึง URL ของ service ที่ deploy แล้ว
          SERVICE_URL=$(gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --format 'value(status.url)')
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT # Output for next steps
          echo "🚀 Application deployed successfully!" # แสดงข้อความสำเร็จ
          echo "📱 Service URL: $SERVICE_URL" # แสดง URL ของ service
          echo "🏥 Health Check: $SERVICE_URL/health" # แสดง URL สำหรับ health check

      - name: Verify deployment
        run: | # ตรวจสอบว่า deployment ทำงานถูกต้อง
          SERVICE_URL="${{ steps.get_url.outputs.SERVICE_URL }}" # Get URL from previous step
          echo "Waiting for service to be ready..."
          max_attempts=12 # Try for 12 * 10s = 120 seconds (2 minutes)
          attempt_num=1
          wait_seconds=10
          while [ $attempt_num -le $max_attempts ]; do
            echo "Attempt $attempt_num/$max_attempts: Testing health endpoint $SERVICE_URL/health"
            response_code=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL/health")
            if [ "$response_code" -eq 200 ]; then
              echo "✅ Health check successful!"
              exit 0
            fi
            echo "Health check failed with status $response_code. Waiting $wait_seconds seconds..."
            sleep $wait_seconds
            attempt_num=$((attempt_num+1))
          done
          echo "⚠️ Health check failed after $max_attempts attempts, but deployment completed. Please check the service manually."
          # Optionally, you can make the workflow fail if health check fails after retries:
          # exit 1